[build]
  command = "pip install -r requirements.txt && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"

# Redirecciones para soportar use_directory_urls
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
